### ISSUE TITLE
Validate YML files before loading

### ISSUE THREAD

**Issue by krzysztof-magosa** [vagrant-dotvm/vagrant-dotvm#28]
At the moment syntax error in YML file raises exception.
It should be human friendly message what's wrong.

```
/opt/vagrant/embedded/lib/ruby/2.0.0/psych.rb:205:in `parse': (<unknown>): mapping values are not allowed in this context at line 3 column 8 (Psych::SyntaxError)
    from /opt/vagrant/embedded/lib/ruby/2.0.0/psych.rb:205:in `parse_stream'
    from /opt/vagrant/embedded/lib/ruby/2.0.0/psych.rb:153:in `parse'
    from /opt/vagrant/embedded/lib/ruby/2.0.0/psych.rb:129:in `load'
    from /Users/hexio/.vagrant.d/gems/gems/vagrant-dotvm-0.35.1/lib/vagrant-dotvm/dotvm.rb:69:in `block (2 levels) in load_projects'
    from /Users/hexio/.vagrant.d/gems/gems/vagrant-dotvm-0.35.1/lib/vagrant-dotvm/dotvm.rb:66:in `each'
    from /Users/hexio/.vagrant.d/gems/gems/vagrant-dotvm-0.35.1/lib/vagrant-dotvm/dotvm.rb:66:in `block in load_projects'
    from /Users/hexio/.vagrant.d/gems/gems/vagrant-dotvm-0.35.1/lib/vagrant-dotvm/dotvm.rb:48:in `each'
    from /Users/hexio/.vagrant.d/gems/gems/vagrant-dotvm-0.35.1/lib/vagrant-dotvm/dotvm.rb:48:in `load_projects'
    from /Users/hexio/.vagrant.d/gems/gems/vagrant-dotvm-0.35.1/lib/vagrant-dotvm/dotvm.rb:12:in `inject'
    from /Users/hexio/.dotvm/Vagrantfile:5:in `block in <top (required)>'
    from /opt/vagrant/embedded/gems/gems/vagrant-1.7.4/lib/vagrant/config/v2/loader.rb:37:in `call'
    from /opt/vagrant/embedded/gems/gems/vagrant-1.7.4/lib/vagrant/config/v2/loader.rb:37:in `load'
    from /opt/vagrant/embedded/gems/gems/vagrant-1.7.4/lib/vagrant/config/loader.rb:103:in `block (2 levels) in load'
    from /opt/vagrant/embedded/gems/gems/vagrant-1.7.4/lib/vagrant/config/loader.rb:97:in `each'
    from /opt/vagrant/embedded/gems/gems/vagrant-1.7.4/lib/vagrant/config/loader.rb:97:in `block in load'
    from /opt/vagrant/embedded/gems/gems/vagrant-1.7.4/lib/vagrant/config/loader.rb:94:in `each'
    from /opt/vagrant/embedded/gems/gems/vagrant-1.7.4/lib/vagrant/config/loader.rb:94:in `load'
    from /opt/vagrant/embedded/gems/gems/vagrant-1.7.4/lib/vagrant/vagrantfile.rb:28:in `initialize'
    from /opt/vagrant/embedded/gems/gems/vagrant-1.7.4/lib/vagrant/environment.rb:689:in `new'
    from /opt/vagrant/embedded/gems/gems/vagrant-1.7.4/lib/vagrant/environment.rb:689:in `vagrantfile'
    from /opt/vagrant/embedded/gems/gems/vagrant-1.7.4/lib/vagrant/environment.rb:441:in `host'
    from /opt/vagrant/embedded/gems/gems/vagrant-1.7.4/lib/vagrant/environment.rb:207:in `block in action_runner'
    from /opt/vagrant/embedded/gems/gems/vagrant-1.7.4/lib/vagrant/action/runner.rb:33:in `call'
    from /opt/vagrant/embedded/gems/gems/vagrant-1.7.4/lib/vagrant/action/runner.rb:33:in `run'
    from /opt/vagrant/embedded/gems/gems/vagrant-1.7.4/lib/vagrant/environment.rb:428:in `hook'
    from /opt/vagrant/embedded/gems/gems/vagrant-1.7.4/lib/vagrant/environment.rb:671:in `unload'
    from /opt/vagrant/embedded/gems/gems/vagrant-1.7.4/bin/vagrant:177:in `ensure in <main>'
    from /opt/vagrant/embedded/gems/gems/vagrant-1.7.4/bin/vagrant:177:in `<main>'
```

**Comment by krzysztof-magosa** [comment]
Fixed in 0.36.0.pre
